ALTER TABLE `garments` ADD `garment_type` text DEFAULT '' NOT NULL;--> statement-breakpoint
UPDATE `garments` SET `garment_type` = CASE
  WHEN lower(`name`) LIKE '%blazer%' THEN 'Blazer'
  WHEN `category` = 'Tailoring' THEN 'Suit Jacket'
  WHEN lower(`name`) LIKE '%hoodie%' OR (`category` = 'Tops' AND lower(`name`) LIKE '%hooded%') THEN 'Hoodie'
  WHEN lower(`name`) LIKE '%crewneck%' OR lower(`name`) LIKE '%sweatshirt%' THEN 'Sweatshirt'
  WHEN lower(`name`) LIKE '%sweater%' OR lower(`name`) LIKE '%knit%' THEN 'Sweater'
  WHEN lower(`name`) LIKE '%tee%' OR lower(`name`) LIKE '%t-shirt%' THEN 'T-shirt'
  WHEN `category` = 'Tops' AND lower(`name`) LIKE '%shirt%' THEN 'Shirt'
  WHEN `category` = 'Tops' THEN 'Top'
  WHEN lower(`name`) LIKE '%parka%' THEN 'Parka'
  WHEN lower(`name`) LIKE '%bomber%' OR lower(`name`) LIKE '%ma-1%' OR lower(`name`) LIKE '%blouson%' THEN 'Bomber'
  WHEN lower(`name`) LIKE '%cape%' THEN 'Cape'
  WHEN lower(`name`) LIKE '%poncho%' THEN 'Poncho'
  WHEN lower(`name`) LIKE '%coat%' OR lower(`name`) LIKE '%peacoat%' OR lower(`name`) LIKE '%trench%' THEN 'Coat'
  WHEN `category` = 'Outerwear' THEN 'Jacket'
  WHEN lower(`name`) LIKE '%jeans%' OR lower(`name`) LIKE '%denim%' THEN 'Jeans'
  WHEN lower(`name`) LIKE '%chino%' THEN 'Chinos'
  WHEN lower(`name`) LIKE '%skirt%' THEN 'Skirt'
  WHEN lower(`name`) LIKE '%short%' THEN 'Shorts'
  WHEN `category` = 'Bottoms' THEN 'Trousers'
  WHEN lower(`name`) LIKE '%sneaker%' THEN 'Sneakers'
  WHEN lower(`name`) LIKE '%boot%' THEN 'Boots'
  WHEN lower(`name`) LIKE '%pump%' OR lower(`name`) LIKE '%heel%' THEN 'Heels'
  WHEN lower(`name`) LIKE '%sandal%' THEN 'Sandals'
  WHEN `category` = 'Footwear' THEN 'Shoes'
  WHEN lower(`name`) LIKE '%tote%' OR lower(`name`) LIKE '%bag%' THEN 'Bag'
  WHEN lower(`name`) LIKE '%cap%' OR lower(`name`) LIKE '%beanie%' OR lower(`name`) LIKE '%hat%' THEN 'Hat'
  WHEN lower(`name`) LIKE '%sunglass%' OR lower(`name`) LIKE '%glasses%' THEN 'Glasses'
  ELSE 'Accessory'
END;--> statement-breakpoint
CREATE INDEX `garments_owner_type_idx` ON `garments` (`owner_id`,`garment_type`);
