import { LegalContact, LegalPage } from "../legal-page";
import Link from "next/link";
import { legalReady } from "../../shared/legal";
export const metadata = { title: "Términos de uso | Formé", robots: { index: legalReady, follow: true } };
export default function TermsPage() {
  return <LegalPage title="Términos de uso" intro="Las reglas para usar Formé, cuidar tus fotos y compartir tu closet.">
    <section><h2>1. Formé y tu cuenta</h2><LegalContact /><p>Formé permite digitalizar prendas, combinarlas en el Canvas y guardar o compartir looks. Al crear una cuenta o aceptar una nueva versión, aceptas estos términos. Puedes consultar la <Link href="/privacidad">Política de privacidad</Link> antes de decidir.</p><p>Debes tener capacidad legal para contratar o contar con la autorización y representación que exija la ley. Proporciona datos veraces, protege el acceso a tu cuenta de Google y avísanos si detectas accesos no autorizados. No crees cuentas para suplantar a otra persona o eludir restricciones.</p></section>
    <section><h2>2. Tus fotos y tu contenido</h2><p>Conservas los derechos que te correspondan sobre las fotos, textos y demás contenido que subes. Usar Formé no transfiere su propiedad a Formé. Solo debes subir contenido propio o para el que tengas los permisos necesarios, incluidos los derechos de imagen de las personas que aparezcan.</p><p>Nos autorizas, de forma no exclusiva y sin regalías, a alojar, copiar, analizar, recortar y transformar ese contenido únicamente para prestarte las funciones que solicitas, como digitalizar una prenda, guardar un look o mostrarlo cuando decidas publicarlo. Esta autorización se extiende a los proveedores técnicos necesarios para esas funciones y dura mientras sea necesaria para prestarlas, con las limitaciones de conservación explicadas en la política de privacidad.</p><p>No nos concedes un permiso general para vender tus fotos, usarlas en publicidad o entrenar modelos propios. Cualquier uso adicional que requiera autorización se te solicitará por separado. Una foto publicada tampoco concede a otras personas una licencia para explotarla comercialmente.</p></section>
    <section><h2>3. Lo que decides publicar</h2><p>Tu perfil comienza privado. Tú eliges si lo haces público, si aparece en la búsqueda y qué prendas o looks compartes. Un look público muestra las imágenes de las prendas que lo componen, aunque esas prendas no estén publicadas por separado en tu closet.</p><p>Al publicar o compartir un enlace o una imagen, otras personas pueden verlo, copiarlo o redistribuirlo. Puedes retirar la publicación en Formé, pero no podemos recuperar copias que terceros ya hayan guardado. Las fotos originales de las prendas no se muestran en el perfil público.</p></section>
    <section id="usernames"><h2>4. Nombres de usuario y marcas</h2><p>Un @usuario es un identificador dentro de Formé. Su asignación no otorga propiedad, exclusividad comercial, derechos de marca ni un derecho permanente a conservarlo. Queda prohibido registrar, acumular, vender, alquilar o transferir @usuarios para especular con nombres de marcas, empresas, personas u otras identidades, o pedir dinero a cambio de liberarlos.</p><p><strong>Formé se reserva el derecho de reservar, rechazar, retirar, modificar o reasignar cualquier @usuario, a su exclusivo criterio y sin requerir la autorización de su titular</strong>, para prevenir o corregir suplantaciones, confusión sobre una identidad o afiliación, infracciones de derechos, acaparamiento, especulación o incumplimientos de estas reglas, así como para proteger identificadores oficiales o resolver necesidades técnicas del servicio.</p><p>La evaluación y la decisión sobre el identificador corresponden a Formé. No es necesario que una marca presente un reclamo para que actuemos. Te comunicaremos el cambio y su motivo para que puedas contactarnos si consideras que existe un error. La asignación anterior no genera por sí sola un derecho a compensación; esto no limita los derechos irrenunciables que reconozca la ley ni el acceso a las autoridades competentes.</p><p>Mencionar una marca en una prenda no acredita una relación comercial, patrocinio ni autenticidad. Los derechos sobre nombres y signos distintivos pertenecen a sus respectivos titulares.</p></section>
    <section><h2>5. Uso permitido y moderación</h2><p>No uses Formé para infringir derechos de autor, privacidad o imagen; publicar contenido ilícito; acosar, discriminar o suplantar; distribuir archivos maliciosos; acceder a cuentas ajenas; extraer masivamente contenido sin autorización; ni eludir límites técnicos o de créditos.</p><p>Podemos retirar contenido o restringir una cuenta cuando exista un incumplimiento, un riesgo de seguridad o una obligación legal. La medida debe corresponder al motivo y su gravedad. Te informaremos del motivo y de cómo contactarnos, salvo que una prohibición legal o la prevención de un riesgo inmediato lo impidan. Puedes reportar una infracción indicando el enlace, los hechos y los derechos afectados mediante el contacto de esta página.</p></section>
    <section><h2>6. Digitalización e inteligencia artificial</h2><p>La IA puede interpretar mal una prenda o modificar detalles, colores, proporciones o textos. Revisa los resultados antes de usarlos. Las imágenes son representaciones digitales: no certifican medidas físicas, talla, ajuste, materiales o autenticidad de una prenda. Las correcciones manuales de tamaño se guardan para esa prenda en tu cuenta y tienen prioridad en las siguientes composiciones automáticas.</p><p>Formé está en beta y puede presentar fallos o interrupciones. Esto no elimina nuestra responsabilidad legal ni los derechos que tengas como consumidor.</p></section>
    <section><h2>7. Créditos y servicios de pago</h2><p>Los límites, precios y condiciones aplicables se muestran antes de contratar. Los créditos sirven para digitalizar prendas dentro de Formé; no son dinero ni un producto de inversión. Un crédito se descuenta cuando la prenda queda lista. Los reintentos automáticos del sistema no consumen créditos adicionales.</p><p>Solicitar información sobre un plan no equivale a contratarlo ni autoriza un cobro. Cualquier compra, renovación, vencimiento de créditos o condición de cancelación debe informarse antes de que la aceptes. Se respetan las condiciones de lo ya contratado y los derechos legales de devolución o reparación que correspondan.</p></section>
    <section><h2>8. Cambios, cierre y contacto</h2><p>Podemos actualizar estos términos por cambios funcionales, técnicos, de seguridad o legales. Indicaremos la fecha y versión. Los cambios sustanciales se comunicarán antes de aplicarse y se solicitará una nueva aceptación cuando corresponda. No se utilizará una actualización para quitar derechos adquiridos o aplicar nuevas finalidades de tratamiento sin la base legal necesaria.</p><p>Puedes dejar de usar Formé y solicitar el cierre de tu cuenta o la supresión de datos mediante el contacto indicado. Para controversias se aplica la legislación peruana, sin desplazar normas obligatorias que te protejan ni limitar tu derecho a acudir a Indecopi, a la Autoridad Nacional de Protección de Datos Personales o a la autoridad competente.</p></section>
  </LegalPage>;
}
