import type { GarmentCategory } from "./garments";

export type ImportedGarmentEntry = {
  file: string;
  name: string;
  category: GarmentCategory;
  color: string;
  brand?: string;
};

// Lote completo auditado contra las 106 prendas fuente de Pants & Sneakers.
// Los nombres son descriptivos y se pueden corregir desde la ficha de prenda.
export const importedGarments20260718: ImportedGarmentEntry[] = [
  { file: "001_DSC01931.webp", name: "Short negro recto", category: "Bottoms", color: "Black" },
  { file: "002_DSC01934.webp", name: "Short gráfico verde", category: "Bottoms", color: "Black / Green" },
  { file: "003_DSC01935.webp", name: "Short cargo gris", category: "Bottoms", color: "Grey" },
  { file: "004_DSC01936.webp", name: "Camisa utility oliva", category: "Tops", color: "Olive" },
  { file: "005_DSC01937.webp", name: "Short rosado", category: "Bottoms", color: "Pink" },
  { file: "006_DSC01938.webp", name: "Cardigan rosado", category: "Tops", color: "Pink" },
  { file: "007_DSC01940.webp", name: "Jogger marrón", category: "Bottoms", color: "Brown" },
  { file: "008_DSC01941.webp", name: "Falda plisada negra", category: "Bottoms", color: "Black" },
  { file: "009_DSC01942.webp", name: "Pantalón gráfico geométrico", category: "Bottoms", color: "Black / Grey" },
  { file: "010_DSC01943.webp", name: "Jean gris claro", category: "Bottoms", color: "Light grey" },
  { file: "011_DSC01944.webp", name: "Pantalón negro ancho", category: "Bottoms", color: "Black" },
  { file: "012_DSC01945.webp", name: "Falda plisada corta", category: "Bottoms", color: "Black" },
  { file: "013_DSC01946.webp", name: "Short drapeado negro", category: "Bottoms", color: "Black" },
  { file: "014_DSC01947.webp", name: "Falda plisada midi", category: "Bottoms", color: "Black" },
  { file: "015_DSC01948.webp", name: "Overol negro", category: "Bottoms", color: "Black" },
  { file: "016_DSC01949.webp", name: "Botas Chelsea negras", category: "Footwear", color: "Black" },
  { file: "017_DSC01950.webp", name: "T-shirt blanca minimal", category: "Tops", color: "White" },
  { file: "018_DSC01952.webp", name: "Top blanco sin mangas", category: "Tops", color: "White" },
  { file: "019_DSC01953.webp", name: "Polo manga larga salvia", category: "Tops", color: "Sage" },
  { file: "020_DSC01955.webp", name: "Polo navy", category: "Tops", color: "Navy" },
  { file: "021_DSC01956.webp", name: "T-shirt gris jaspe", category: "Tops", color: "Charcoal grey" },
  { file: "022_DSC01957.webp", name: "Tank negro", category: "Tops", color: "Black" },
  { file: "023_DSC01958.webp", name: "T-shirt gris oversized", category: "Tops", color: "Light grey" },
  { file: "024_DSC01959.webp", name: "Sweatshirt negro con cuello", category: "Tops", color: "Black" },
  { file: "025_DSC01960.webp", name: "T-shirt turquesa gráfica", category: "Tops", color: "Teal" },
  { file: "026_DSC01961.webp", name: "T-shirt negra gráfica", category: "Tops", color: "Black" },
  { file: "027_DSC01962.webp", name: "T-shirt roja gráfica", category: "Tops", color: "Red" },
  { file: "028_DSC01963.webp", name: "T-shirt crema The Child", category: "Tops", color: "Cream" },
  { file: "029_DSC01965.webp", name: "Camisa tartán sin mangas", category: "Tops", color: "Red / Black" },
  { file: "030_DSC01966.webp", name: "Camisa abstracta rosada", category: "Tops", color: "Pink / Black" },
  { file: "031_DSC01967.webp", name: "Sobrecamisa gráfica larga", category: "Outerwear", color: "Multicolor" },
  { file: "032_DSC01969.webp", name: "Hoodie amarillo pálido", category: "Tops", color: "Pale yellow" },
  { file: "033_DSC01970.webp", name: "Hoodie blanco mangas gráficas", category: "Tops", color: "White / Multicolor" },
  { file: "034_DSC01971.webp", name: "Hoodie gris gráfico", category: "Tops", color: "Grey" },
  { file: "035_DSC01972.webp", name: "Sweatshirt crema gráfico", category: "Tops", color: "Cream" },
  { file: "036_DSC01973.webp", name: "Sweatshirt mostaza", category: "Tops", color: "Mustard" },
  { file: "037_DSC01975.webp", name: "Hoodie azul gráfico", category: "Tops", color: "Blue" },
  { file: "038_DSC01976.webp", name: "Hoodie gris cargo", category: "Tops", color: "Grey" },
  { file: "039_DSC01977.webp", name: "Hoodie negro gráfico", category: "Tops", color: "Black" },
  { file: "040_DSC01980.webp", name: "Hoodie taupe", category: "Tops", color: "Taupe" },
  { file: "041_DSC01981.webp", name: "Camisa verde gráfica", category: "Tops", color: "Dark green" },
  { file: "042_DSC01982.webp", name: "T-shirt neón gráfica", category: "Tops", color: "Neon yellow" },
  { file: "043_DSC01983.webp", name: "Hoodie beige", category: "Tops", color: "Beige" },
  { file: "044_DSC01984.webp", name: "Camisa camp multicolor", category: "Tops", color: "Black / Multicolor" },
  { file: "045_DSC01985.webp", name: "Camisa texturada estampada", category: "Tops", color: "Brown / Black" },
  { file: "046_DSC01986.webp", name: "T-shirt blanca básica", category: "Tops", color: "White" },
  { file: "047_DSC01989.webp", name: "Sneakers plateadas", category: "Footwear", color: "Silver / Multicolor" },
  { file: "048_DSC01992.webp", name: "Botas Chelsea negras", category: "Footwear", color: "Black" },
  { file: "049_DSC01993.webp", name: "Sneakers blancas y azules", category: "Footwear", color: "White / Blue" },
  { file: "050_DSC01994.webp", name: "Botas combat bicolor", category: "Footwear", color: "Black / Cream" },
  { file: "051_DSC01995.webp", name: "Sneakers técnicas grises", category: "Footwear", color: "Grey / Multicolor" },
  { file: "052_DSC01996.webp", name: "High-tops azules y doradas", category: "Footwear", color: "Blue / Gold" },
  { file: "053_DSC01997.webp", name: "High-tops blancas", category: "Footwear", color: "White / Beige" },
  { file: "054_DSC01998.webp", name: "Sneakers negras swoosh turquesa", category: "Footwear", color: "Black / Teal", brand: "Nike" },
  { file: "055_DSC01999.webp", name: "Sneakers pastel multicolor", category: "Footwear", color: "Multicolor", brand: "Nike" },
  { file: "056_DSC02000.webp", name: "Sneakers técnicas negras", category: "Footwear", color: "Black" },
  { file: "057_DSC02001.webp", name: "Derbies con suela verde", category: "Footwear", color: "Black / Pale green" },
  { file: "058_DSC02003.webp", name: "High-tops tipográficas", category: "Footwear", color: "White / Black" },
  { file: "059_DSC02004.webp", name: "Botas negras suela ámbar", category: "Footwear", color: "Black / Amber" },
  { file: "060_DSC02005.webp", name: "High-tops multicolor", category: "Footwear", color: "Blue / Red / Cream", brand: "Nike" },
  { file: "061_DSC02008.webp", name: "Slingbacks negras de pelo", category: "Footwear", color: "Black" },
  { file: "062_DSC02009.webp", name: "Sandalias técnicas blancas", category: "Footwear", color: "White / Black" },
  { file: "063_DSC02011.webp", name: "Sneakers blancas y champagne", category: "Footwear", color: "White / Champagne", brand: "Nike" },
  { file: "064_DSC02013.webp", name: "Sneakers knit negras", category: "Footwear", color: "Black" },
  { file: "065_DSC02015.webp", name: "Mules negras puntiagudas", category: "Footwear", color: "Black" },
  { file: "066_DSC02017.webp", name: "High-tops bronce y naranja", category: "Footwear", color: "Bronze / Orange", brand: "Nike" },
  { file: "067_DSC02019.webp", name: "Sneakers negras clásicas", category: "Footwear", color: "Black", brand: "Nike" },
  { file: "068_DSC02022.webp", name: "High-tops amarillas", category: "Footwear", color: "Yellow / Black" },
  { file: "069_DSC02024.webp", name: "Sneakers negras air sole", category: "Footwear", color: "Black / Green", brand: "Nike" },
  { file: "070_DSC02026.webp", name: "Sneakers negras con verde neón", category: "Footwear", color: "Black / Beige / Neon green", brand: "Nike" },
  { file: "071_DSC02028.webp", name: "Bucket hat gráfico", category: "Accessories", color: "Black / White" },
  { file: "072_DSC02029.webp", name: "Bucket hat con parche", category: "Accessories", color: "Black" },
  { file: "073_DSC01894.webp", name: "Pantalón cargo grafito", category: "Bottoms", color: "Charcoal grey" },
  { file: "074_DSC01896.webp", name: "Pantalón blanco ancho", category: "Bottoms", color: "White" },
  { file: "075_DSC01897.webp", name: "Pantalón beige recto", category: "Bottoms", color: "Beige" },
  { file: "076_DSC01898.webp", name: "Jogger negro panelado", category: "Bottoms", color: "Black / Grey" },
  { file: "077_DSC01899.webp", name: "Pantalón negro ancho", category: "Bottoms", color: "Black" },
  { file: "078_DSC01900.webp", name: "Jean azul flare", category: "Bottoms", color: "Denim blue" },
  { file: "079_DSC01901.webp", name: "Pantalón de cuero negro", category: "Bottoms", color: "Black" },
  { file: "080_DSC01903.webp", name: "Pantalón negro recto", category: "Bottoms", color: "Black" },
  { file: "081_DSC01904.webp", name: "Pantalón negro slim", category: "Bottoms", color: "Black" },
  { file: "082_DSC01905.webp", name: "Pantalón azul recto", category: "Bottoms", color: "Blue" },
  { file: "083_DSC01906.webp", name: "Jogger negro con broches", category: "Bottoms", color: "Black" },
  { file: "084_DSC01908.webp", name: "Jogger rosa viejo", category: "Bottoms", color: "Dusty rose" },
  { file: "085_DSC01909.webp", name: "Short denim azul", category: "Bottoms", color: "Denim blue" },
  { file: "086_DSC01910.webp", name: "Short cargo oliva", category: "Bottoms", color: "Olive" },
  { file: "087_DSC01911.webp", name: "Short boxer marfil", category: "Bottoms", color: "Ivory" },
  { file: "088_DSC01912.webp", name: "Short piedra", category: "Bottoms", color: "Stone" },
  { file: "089_DSC01913.webp", name: "Short celeste", category: "Bottoms", color: "Light blue" },
  { file: "090_DSC01914.webp", name: "Short verde", category: "Bottoms", color: "Green" },
  { file: "091_DSC01915.webp", name: "Short crema", category: "Bottoms", color: "Cream" },
  { file: "092_DSC01916.webp", name: "Short gris carbón", category: "Bottoms", color: "Charcoal grey" },
  { file: "093_DSC01917.webp", name: "Short sastre gris", category: "Bottoms", color: "Grey" },
  { file: "094_DSC01918.webp", name: "Jogger blanco rayado", category: "Bottoms", color: "White / Light blue" },
  { file: "095_DSC01919.webp", name: "Pantalón camel", category: "Bottoms", color: "Camel" },
  { file: "096_DSC01920.webp", name: "Pantalón gris recto", category: "Bottoms", color: "Grey" },
  { file: "097_DSC01922.webp", name: "Pantalón de cuero slim", category: "Bottoms", color: "Black" },
  { file: "098_DSC01923.webp", name: "Pantalón negro ceñido", category: "Bottoms", color: "Black" },
  { file: "099_DSC01924.webp", name: "Pantalón negro plisado", category: "Bottoms", color: "Black" },
  { file: "100_DSC01925.webp", name: "Pantalón negro amplio", category: "Bottoms", color: "Black" },
  { file: "101_DSC01926.webp", name: "Jogger negro", category: "Bottoms", color: "Black" },
  { file: "102_DSC01927.webp", name: "Cargo camuflado", category: "Bottoms", color: "Camouflage" },
  { file: "103_DSC01928.webp", name: "Cargo jogger gris", category: "Bottoms", color: "Grey" },
  { file: "104_DSC01930.webp", name: "Cargo camuflado oscuro", category: "Bottoms", color: "Dark camouflage" },
  { file: "105_DSC01932.webp", name: "Short negro deportivo", category: "Bottoms", color: "Black" },
  { file: "106_DSC01968.webp", name: "Sobrecamisa camuflada", category: "Outerwear", color: "Camouflage" },
];
